print "This is just a test, IGNORE IT ok?"
print "Hey, seriously dont read it"
print "End it..."
print "                         ????"
print "Can you stop reading? Im about to said a SECRET shhh"
print "Alright noone is seen :D"
print "K?"
print "E... ok, since you read all way down I tell you the secret"
print "                   (ignore me)"
print "In just a second.."
print "Shhhh"
print "                          0_o"
print "And"
print "                          nyan"
print "Look at the first letter"
print "In"
print "Every sentence, BLOWMIND ! "
